device: 0
cpu_num: 16

image_size: [640, 640]

out_path: runs
exist_ok: True

lucky_number: 10
use_wandb: True
use_tensorboard: False

weight: True # Path to weight or True for auto, False for no pretrained weight

dataloader:
  num_workers: 4
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 2
  batch_size: 8